version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run format
          command: npm run format -l
      - run:
          name: Run test
          command: npm run test
